//
//  RandomNumberGenerator.swift
//  FrameworkOne
//
//  Created by Stephen Anthony on 28/07/2025.
//

import Foundation

/// Generates random numbers.
public final class RandomNumberGenerator {
    
    public init() {}
    
    /// Requests that the receiver generate a random number.
    /// - Returns: The random number generated by the receiver.
    public func generateRandomNumber() -> Int {
        Int.random(in: 100...1000)
    }
}
